version: "3"
services:
## --------------app------------------ ##
  app:
    build:
      context: ./bin/app
    container_name: ${project_name}-app
    restart: 'always'
    environment:
      DB_PORT: ${MYSQL_PORT}
      DB_ADD: db
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB: ${MYSQL_DATABASE}
      WEBSERVICE_PORT : 6060
    ports:
      - 6060:6060
    links:
      - db
      - php_apache
#   volumes:
#      - ./mylibs.conf:/etc/ld.so.conf.d/mylibs.conf
    depends_on:
      - db
      - phpmyadmin
      - php_apache
## --------------database----------------- ## 
  db:
    build:
      context: ./bin/db
    container_name: ${project_name}-database
    restart: 'always'
    links:
      - app 
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
#     MYSQL_USER: ${MYSQL_USER}
#     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/db/data:/var/lib/mysql
      - ./logs/database-logs:/var/log/mysql
      - ./database/Test.sql:/docker-entrypoint-initdb.d/schema.sql:ro
## ----------------phpmyadmin------------- ##
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${project_name}-phpmyadmin
    restart: 'always'
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "800:80"
#    volumes:
#      - ./config/phpmyadmin:/etc/phpmyadmin/apache.conf:rw
## ----------------php-apache------------- ## 
  php_apache:
    build:
      context: ./bin/php-apache
    container_name: ${project_name}-php-apache
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    depends_on:
      - db 
    volumes:
      - ./www/:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
#      - ./config/phpmyadmin.conf:/etc/apache2/conf-available/phpmyadmin.conf
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}




